name: tflint_and_tfsec

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  schedule:
    - cron: '45 17 * * 1'

jobs:
  tflint:
    name: tflint
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      name: Checkout source code

    - uses: terraform-linters/setup-tflint@v1
      name: Setup TFLint
      working-directory: ./aws/ubuntu_development_vm
      with:
        tflint_version: latest

    - name: Show tflint version
      working-directory: ./aws/ubuntu_development_vm
      run: tflint --version

    - name: Initialize TFLint
      working-directory: ./aws/ubuntu_development_vm
      run: tflint --init

    - name: Run TFLint
      working-directory: ./aws/ubuntu_development_vm
      run: tflint --log-level=info -f compact

  tfsec:
    name: tfsec (with sarif report)
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write

    steps:
      - name: Clone repo
        uses: actions/checkout@v2

      - name: Run tfsec
        uses: tfsec/tfsec-sarif-action@9a83b5c3524f825c020e356335855741fd02745f
        with:
          sarif_file: tfsec.sarif

      - name: Upload tfsec SARIF file
        uses: github/codeql-action/upload-sarif@v1
        with:
          # Path to SARIF file relative to the root of the repository
          sarif_file: tfsec.sarif
